### ISSUE TITLE
Não é possível setar o timeout da requisição

### ISSUE THREAD

**Issue by possatto** [totalvoice/totalvoice-ruby#12]
Não é possível passar nenhum argumento do httparty na requisição. Tenho casos onde um simples get na consulta de saldo chega levar 2 minutos e a conexão é interrompida. Gostaria de poder passar o timeout para não ficar esperando até que a api expire a conexão.

Minha sugestão é poder passar os argumentos do httparty no `initialize` da classe `httparty::API`

```ruby
def initialize(access_token, host = nil, options)
  ...
  @options = {
    headers: {
      "Access-Token" => @access_token,
      "Content-Type" => "application/json",
      "Accept" => "application/json"
    }
  }
  @options.merge!(options)
  ...
end
```

Assim poderíamos chamar a API da seguinte forma:

```ruby
TotalVoice::API.new(access_token, host, { timeout: 10 })
```

**Comment by dilowagner** [comment]
Legal @possatto obrigado pelo feedback
Vamos verificar a implementacao...

Seria otimo se vc conseguisse abrir uma PR com a mudanca, valeu!
Abraço!
