### ISSUE TITLE
Versão do httparty

### ISSUE THREAD

**Issue by ghsmaniotto** [totalvoice/totalvoice-ruby#4]
Olá, tudo certo?

Tive um problema no meu projeto quando adicionei a gem do totalvoice, pois tenho outras gems que utilizam o httparty e isso gerou uma incompatibilidade no projeto pois a versão que voces solicitam esta fixada na 0.16.2. Com isso, gostaria de saber se tem algum motivo específico para que a versão do httparty seja exatamente a 0.16.2?

Desde já agradeço a  atenção!

**Comment by dilowagner** [comment]
Olá @ghsmaniotto tudo bem!?
Foi mais por uma questão de compatibildade mesmo...
Vamos verificar a possibilidade atualizá-la e geramos uma nova versão... 

Qual versão você está utiizando?

**Comment by ghsmaniotto** [comment]
Tudo certo @dilowagner  :)
Perfeito!! Estamos usando a ultima versão () pois outras dependências usam a ultima versão dele, aí por ser definida uma versão específica no gemfile de vocês, da conflito :/

Talvez se a versão do httparty for '>= 0.16.2' já resolveria os conflitos :)

**Comment by dilowagner** [comment]
Obrigado pela contribuição @ghsmaniotto 
Gerada a versão 1.4.1

Qualquer problema nos avise...
Abraço!

**Comment by ghsmaniotto** [comment]
Shooow de bola!! Muuito obrigado @dilowagner :)

Pode deixar que qualquer problema chamaremos!!

Abraços!
